---
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/s4heid/bosh-azure-stemcell-mirror
options:
  tag_filter_pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
        - ci
        - docs
  commit_groups:
    title_maps:
      chore: Chores
      ci: Continous Integration
      docs: Documentation
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - #
  refs:
    actions:
      - Closes
      - closes
      - Fixes
      - fixes
      - Resolves
      - resolves
  notes:
    keywords:
      - BREAKING CHANGE